USE GENDERSTATS_DB;
DROP TABLE IF EXISTS ADOLESCENT_FERTILITY;
CREATE TABLE ADOLESCENT_FERTILITY
AS
SELECT * FROM GENDER_STATS
WHERE INDICATOR_CODE='SP.ADO.TFRT';

CREATE TABLE ADOLESCENT_FERTILITY
(COUNTRY_NAME STRING,
YEAR_1960 DECIMAL,
YEAR_2015 DECIMAL,
Percent_Difference DECIMAL);

SELECT country_name, year_1960, year_2015, ((year_1960-year_2015)/1000)*100 AS Percent_Difference
FROM GENDER_STATS
WHERE INDICATOR_CODE='SP.ADO.TFRT';